# start with docker-compose -f tokentransfer.yml up -d

version: '3'

services:

  appchain:
    build: 
      context: ./appchain
      args:
        configyml: ./config.yml
    container_name: appchain
    image: "appchain_i"
    ports:
      - "26657:26657"
      - "1317:1317"
      - "4500:4500"
      - "9090:9090"
    networks:
      - ibcbanktransfer_net

  relayer_hermes:
    profiles: ["hermes"]
    build: ./relayer_hermes
    container_name: relayer
    image: "relayer_hermes"
    tty: true
    stdin_open: true
    networks:
      - ibcbanktransfer_net

  relayer_go:
    profiles: ["go"]
    build: ./relayer_go
    container_name: relayer
    image: "relayer_go"
    tty: true
    stdin_open: true
    networks:
      - ibcbanktransfer_net

networks:
    ibcbanktransfer_net: