accounts:
  - name: alice
    coins: ["20000token", "200000000stake", "200000000token1"]
    mnemonic: "cinamon legend ..."
  - name: bob
    coins: ["10000token", "100000000stake", "200000000token1"]
    mnemonic: "define envelope ..."
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake", "100000token1"]
genesis:
  chain_id: "appchain"